# Generated by Django 3.2.8 on 2021-10-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=2)),
                ('preferred_language', models.CharField(default='en', max_length=2)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('customer_comment', models.TextField()),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=5, unique=True)),
                ('unit_group', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('family', 'Family room')], default='double', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.property')),
            ],
            options={
                'ordering': ('property', 'unit_group', 'unit'),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', models.PositiveSmallIntegerField()),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('checkin', models.DateTimeField(null=True)),
                ('checkout', models.DateTimeField(null=True)),
                ('rate_plan', models.CharField(choices=[('flexible', 'Flexible'), ('flexible-family', 'Flexible Family'), ('include-breakfast', 'Include Breakfast'), ('non-refundable', 'Non Refundable'), ('non-refundable-family', 'Non Refundable Family')], default='flexible', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='open', max_length=20)),
                ('travel_purpose', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='web.customer')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='web.property')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='web.unit')),
            ],
        ),
    ]
